os: linux
language: python
python: 3.7
install:
    - pip install -r requirements.txt 
    - pip install -r ci/requirements.txt
    - pip install -r tests/unit/requirements.txt
script:
    - pip install -e .
    - ci/static_checks.sh altimeter
    - ci/test.sh altimeter tests/unit
