os: linux
language: python
python: 3.7
services:
  - docker
env:
  global:
    secure: "jhQUq3Srd75RSLMtE+rrOliqw9n1QfVCFf00J+n4qefC/iCJwG6bagX/jUX/dOEq4yFsl8POfmN6v9+OtQvvTmmwtkfNzl6bpqtZOP/nRTQShbhIUpXMN2Up1eAd6i3g9xfeMEJQZspgUgdoc/E3+51OP7+abTqMIp96qUKEDl7CeTJCNaxJCmPWe5B/doudq2f5N0epTkDE380FsTpitU4JeZz9h/3XrZ0GLIWt0Bv7TpxuwKp8toNVU9mxyFv+1LVBz5tJ6yu+ZvNPdp0zeApIpGl+Vh68GCPlR9cYOw7Rr/f1KyuGQZpqX+U5R+QPikwg/7Vf+YaFrmiy6wzro/YWDaAHIKxy/ld+RLi4rmH/U5WDs4yK7WWFU5lBgFIp2xO6Bra8qd2pEOnoeaDcpKW99VcnypiMIesIZyLuLHVU1htUID0D8HJWNjcHl8WkQv/iinR7CGhMXr3J25ihFipNRo5jH4wfZ44jGKyR0a8Kj0T/jRqt0ntCATKBsbjb4sAka5liIh1P81MJZ7zyXi99WBh96JDfeGlT6jfT727SYjrRzwq+G0Pr8pLSHwgznmcUEjtZRrKv4XjPW1FA6a7Qo9tqS2X/iQn0Rk8H0ciiaP/WTBKqyyuWApo75nStN4Cgrz6roIcUje2mwRcmA/+mpLhtfna7S+PyJbfS+T8="
    secure: "UmN2HxVpIi1PMfHaF9D4NzQaGHmSKhIEi2hzdtGYSRTgN6zE3HCA36hJRiRD74Y7JXPGMfuuKz0kFNJIGBN1YB2g0hYlmRquIUfD4CFsLkpiddC/vu11sBjaBDd0a7T27DYbfeRLXbI5CXSYNL3V7tXgCXfFHgp92TXMe7qLh2/6aRA0I6rwFp7c+g9pblYYAI4mVAj1iMgrq2rmlzXNs0KHkerIt5ZCO933meXaaxoqitjTL4hRMY2Nww4XF3FKVwmISDTxKOO/iGwtUSXvle3OrUCr0U8x2dY27fu65JLVoDJHp17GBQOfRjSAnnWaNkykPRsUGWEPSzjiX9eBcszWpXLM7D+P9R8Bk7KA2vh7aj6jrBhrbFiVMWatSDi3oRhChWl7NIfEQjmu3cUs3IkEIEzeIBmxXIhunXnqvPApBAurldXVga9b7ekBNt/WNP80JpNE11X9paO8J9hFjaqnUopjnwFl+HWt1cahg7gx4sz9YuTlpFbqyeAKY0wJ/FeQ+1RoXfWrP4UlApbLUAEoZn6WfoPnM858FqR7LzuWax1LeatoLwYB2oHUZRxu/ZCzf7/xCbvbVH0K4DO5TEDLsDmE20qrHgZprnPAl9QsoA8N484Nbu1p1tMGqoYCVgTgW+0cOiN2p49bl1oasqEaOo3UE7Ts7WJCAb5bIVc="
install:
    - pip install -r requirements.txt
    - pip install -r ci/requirements.txt
    - pip install -r doc/requirements.txt
    - pip install -r tests/unit/requirements.txt
jobs:
    include:
#        - stage: static-analysis
#          script: ci/static_checks.sh
#
#        - stage: test
#          script: ci/test.sh
#
#        - stage: build-doc
#          script:
#              - export PYTHONPATH=.
#              - sphinx-apidoc -f -o doc/source altimeter
#              - sphinx-build doc/source doc/html -E -W
#
#        # rc packages are published if the tag matches n.n.n-rcn
#        - stage: deploy-pypi-release-candidate
#          if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ AND type = push AND fork = false
#          script:
#              - sed -i "s/LOCALVERSION/${TRAVIS_TAG}/g" setup.py
#          deploy:
#              provider: pypi
#              skip_cleanup: true
#              user: "__token__"
#              password:
#                  secure: "oXWWn+yLy0sZhZrE/Pv3pd4GaoufgLbKZ3HoAWMdudZwK6YI/xikw3wn1yfnuyhcUFGemoE99oE7Xz3+jUmINVElzqnlkpG6/j6FYuPZU4Ca90hyLX9E0Ojw5RYx3PqCOGAtt6qyjRrS7doVyUwAd5hcryKupQrz8fWpfECP11kVxxhk4Bxq08UfZrLGzxsMd0rGL8FiHlV7d4EDW6X8v0t+I6YulqrkW2nyeXQrRie5+01DMxBBwXAF477UvHuDwfjZ/2JH2pk7p3cF0VI0FLfdPe3+k/tuodbGYJr9t3qtl1pqzc4PzC4qfnZIOelnEcWBFIGMzVWjKNdChBu5iqgQGSiY0/R43qNQk66Ioj9++wQKWWlKS+eaqI4A1k182ioSscC17GwyY6OJ0VzU5gengfkk36oBBr0w8JjIsu8piq9/Ea+QRZJMnjYy/tExyAGheVB0QjIhIaJBCb/04igq8s9VOdgWtLBbWdhe/B6XI/3Hl0F1ztJz5078fYYVQr/RuXsQOdiYy4TpIoPSdla3BgW7kwPKetfYd1VGE1tdbLiBtCsJZVjcRLn9yOowze85OmD2eYunKQuCW6SCgSUspoSCuVWoNUrYLlJgXpjuXkPGOXK7Vd2hiw2vRKfSp8YVANpPzUpP8C1Sn29XMnOw5u6hKnOlpCgsen0bemM="
#              skip_existing: true
#              on:
#                  all_branches: true
#                  tags: true
#
        # rc packages are published if the tag matches n.n.n-rcn
        - stage: build-push-docker-image-release-candidate
          if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ AND type = push AND fork = false
          script:
              - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
              - docker build -t altimeter:${TRAVIS_TAG} .
              - docker push altimeter:${TRAVIS_TAG}
#
#        # release packages are published if the tag matches n.n.n
#        - stage: deploy-pypi-release
#          if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ AND type = push AND fork = false
#          script:
#              - sed -i "s/LOCALVERSION/${TRAVIS_TAG}/g" setup.py
#          deploy:
#              provider: pypi
#              skip_cleanup: true
#              user: "__token__"
#              password:
#                  secure: "oXWWn+yLy0sZhZrE/Pv3pd4GaoufgLbKZ3HoAWMdudZwK6YI/xikw3wn1yfnuyhcUFGemoE99oE7Xz3+jUmINVElzqnlkpG6/j6FYuPZU4Ca90hyLX9E0Ojw5RYx3PqCOGAtt6qyjRrS7doVyUwAd5hcryKupQrz8fWpfECP11kVxxhk4Bxq08UfZrLGzxsMd0rGL8FiHlV7d4EDW6X8v0t+I6YulqrkW2nyeXQrRie5+01DMxBBwXAF477UvHuDwfjZ/2JH2pk7p3cF0VI0FLfdPe3+k/tuodbGYJr9t3qtl1pqzc4PzC4qfnZIOelnEcWBFIGMzVWjKNdChBu5iqgQGSiY0/R43qNQk66Ioj9++wQKWWlKS+eaqI4A1k182ioSscC17GwyY6OJ0VzU5gengfkk36oBBr0w8JjIsu8piq9/Ea+QRZJMnjYy/tExyAGheVB0QjIhIaJBCb/04igq8s9VOdgWtLBbWdhe/B6XI/3Hl0F1ztJz5078fYYVQr/RuXsQOdiYy4TpIoPSdla3BgW7kwPKetfYd1VGE1tdbLiBtCsJZVjcRLn9yOowze85OmD2eYunKQuCW6SCgSUspoSCuVWoNUrYLlJgXpjuXkPGOXK7Vd2hiw2vRKfSp8YVANpPzUpP8C1Sn29XMnOw5u6hKnOlpCgsen0bemM="
#              skip_existing: true
#              on:
#                  all_branches: true
#
#        # release packages are published if the tag matches n.n.n
#        - stage: build-push-docker-image-release
#          if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ AND type = push AND fork = false
#          script:
#              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#              - docker build -t altimeter:${TRAVIS_TAG} .
#              - docker tag altimeter:${TRAVIS_TAG} altimeter:latest
#              - docker push altimeter:${TRAVIS_TAG}
#              - docker push altimeter:latest
#
#        # only publish to pages for master with a tag matching a 'real' release.
#        - stage: deploy-github-pages
#          if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ AND type = push AND fork = false
#          script:
#              - export PYTHONPATH=.
#              - sphinx-apidoc -f -o doc/source altimeter
#              - sphinx-build doc/source doc/html -E -W
#              - touch doc/html/.nojekyll
#          deploy:
#              provider: pages
#              skip_cleanup: true
#              github_token: $GITHUB_TOKEN
#              local_dir: doc/html
#              on:
#                  all_branches: true
